// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:96660bff-fcc6-490a-b464-c08da9359cff",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Gszj1OvHj",
    "aws_user_pools_web_client_id": "7lvlu50k3js02k84j39vop3em5",
    "aws_appsync_graphqlEndpoint": "https://bjiikf5ohfffheppzw4oc6b7ha.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "zero-to-deploy-aws-amplify",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://zero-to-deploy-aws-amplify.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
